language:
    - java

jdk:
    - openjdk11
    
addons:
    sonarcloud:
        organization: "gabrielequatrana"
        token: "f9a6955fed7d163379bce04db40367924cd6d954"
  
script:
    - mvn "-Dtest=org/apache/bookkeeper/tests/*Test" -DfailIfNoTests=false clean verify -pl bookkeeper-server -am -e org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=gabrielequatrana_bookkeeper